In [ ]:
import pandas as pd

In [ ]:
x = 10

In [ ]:
y = x * 2.0

print(y)

In [ ]:
if True:
print("oops")

In [ ]:
def add_numbers(a: int, b: int) -> int:
    '''Returns the sum of two integers.'''
    return a + b

In [ ]:
z = add_numbers(2, 3)

z

In [ ]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_1 = _dntk.execute_sql(
  'SELECT * FROM actor',
  'SQL_084F5334_5DBE_41C7_9020_3F66B9418062',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_1

     actor_id first_name     last_name               last_update
0           1   PENELOPE       GUINESS 2017-02-15 06:34:33+00:00
1           2       NICK      WAHLBERG 2017-02-15 06:34:33+00:00
2           3         ED         CHASE 2017-02-15 06:34:33+00:00
3           4   JENNIFER         DAVIS 2017-02-15 06:34:33+00:00
4           5     JOHNNY  LOLLOBRIGIDA 2017-02-15 06:34:33+00:00
..        ...        ...           ...                       ...
195       196       BELA        WALKEN 2017-02-15 06:34:33+00:00
196       197      REESE          WEST 2017-02-15 06:34:33+00:00
197       198       MARY        KEITEL 2017-02-15 06:34:33+00:00
198       199      JULIA       FAWCETT 2017-02-15 06:34:33+00:00
199       200      THORA        TEMPLE 2017-02-15 06:34:33+00:00

[200 rows x 4 columns]

In [ ]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_2 = _dntk.execute_sql(
  'SELECT * FROM customer c WHERE c.active = 1',
  'SQL_084F5334_5DBE_41C7_9020_3F66B9418062',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_2

,customer_id,store_id,first_name,last_name,email,address_id,activebool,create_date,last_update,active
0,1,1,MARY,SMITH,MARY.SMITH@sakilacustomer.org,5,True,2017-02-14,2017-02-15 06:57:20+00:00,1
1,2,1,PATRICIA,JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,6,True,2017-02-14,2017-02-15 06:57:20+00:00,1
2,3,1,LINDA,WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,7,True,2017-02-14,2017-02-15 06:57:20+00:00,1
3,4,2,BARBARA,JONES,BARBARA.JONES@sakilacustomer.org,8,True,2017-02-14,2017-02-15 06:57:20+00:00,1
4,5,1,ELIZABETH,BROWN,ELIZABETH.BROWN@sakilacustomer.org,9,True,2017-02-14,2017-02-15 06:57:20+00:00,1
...,...,...,...,...,...,...,...,...,...,...
579,595,1,TERRENCE,GUNDERSON,TERRENCE.GUNDERSON@sakilacustomer.org,601,True,2017-02-14,2017-02-15 06:57:20+00:00,1
580,596,1,ENRIQUE,FORSYTHE,ENRIQUE.FORSYTHE@sakilacustomer.org,602,True,2017-02-14,2017-02-15 06:57:20+00:00,1
581,597,1,FREDDIE,DUGGAN,FREDDIE.DUGGAN@sakilacustomer.org,603,True,2017-02-14,2017-02-15 06:57:20+00:00,1
582,598,1,WADE,DELVALLE,WADE.DELVALLE@sakilacustomer.org,604,True,2017-02-14,2017-02-15 06:57:20+00:00,1
583,599,2,AUSTIN,CINTRON,AUSTIN.CINTRON@sakilacustomer.org,605,True,2017-02-14,2017-02-15 06:57:20+00:00,1